### PR TITLE
updating to get things building

### PR DESCRIPTION
**Pull request by smoothdeveloper**
metaweather has shut down so I hacked something using open-meteo.

I haven't tested the whole thing beside getting a build using `dotnet build`.

### CODE REVIEW

**Comment by daveyostcom** [comment]
Thanks.  I cloned your clone, but it still fails for me.
```
0 212 Z% dotnet tool restore
Tool 'paket' (version '6.0.0-rc002') was restored. Available commands: paket
Tool 'fable' (version '3.2.1') was restored. Available commands: fable
Tool 'fantomas-tool' (version '4.4.0') was restored. Available commands: fantomas

Restore was successful.
0 213 Z% dotnet run
/Users/yost/p/f#/guido-learns-fsharp2/.paket/Paket.Restore.targets(171,5): error MSB3073: The command "dotnet paket restore" exited with code 137. [/tmp/guido-learns-fsharp2/Build.fsproj]

The build failed. Fix the build errors and run again.
1 214 Z% 
```

**Comment by smoothdeveloper** [comment]
@daveyostcom somehow, you must be in another branch or some other issue; it should pull paket 7.2.1 for example. The other person in #5 confirmed on slack that this PR has unblocked them.

**Comment by daveyostcom** [comment]
@smoothdeveloper 
> @daveyostcom somehow, you must be in another branch or some other issue; it should pull paket 7.2.1 for example. The other person in #5 confirmed on slack that this PR has unblocked them.

Thanks so much!  Something was corrupted in the sdks that were installed. I cleaned out and reinstalled 5 and 7, and now `dotnet run` works.  I get a completely empty web page, tho, at `http://localhost:8085`.

**Comment by daveyostcom** [comment]
I'm getting errors:
```
Z% dotnet run
run Run
Building project with version: LocalBuild
Shortened DependencyGraph for Target Run:
<== Run
   <== InstallClient
      <== Clean

The running order is:
Group - 1
  - Clean
Group - 2
  - InstallClient
Group - 3
  - Run
Starting target 'Clean'
> "/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono" --version (In: false, Out: true, Err: true)
/tmp/p/f#/guido-learns-fsharp5/src/Client> "dotnet" fable clean --yes (In: false, Out: false, Err: false)
Fable: F# to JS compiler 3.2.1
Thanks to the contributor! @markek
This will recursively delete all *.fs.js[.map] files in /tmp/p/f#/guido-learns-fsharp5/src/Client
Deleted .fable
Clean completed! Files deleted: 0
Finished (Success) 'Clean' in 00:00:00.5880970
Starting target 'InstallClient'
.> "/usr/local/bin/npm" install (In: false, Out: false, Err: false)

up to date, audited 899 packages in 3s

62 packages are looking for funding
  run `npm fund` for details

35 vulnerabilities (1 low, 5 moderate, 24 high, 5 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
Finished (Success) 'InstallClient' in 00:00:03.1918552
Starting target 'Run'
/tmp/p/f#/guido-learns-fsharp5/src/Shared> "dotnet" build (In: false, Out: false, Err: false)
MSBuild version 17.6.8+c70978d4d for .NET
  Determining projects to restore...
  Paket version 7.2.1+8e4eb74b42fbd45f39f7afce9184c16ebb65f16c
  Restoring /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fsproj
  Starting restore process.
  Total time taken: 0 milliseconds
  All projects are up-to-date for restore.
  Paket version 7.2.1+8e4eb74b42fbd45f39f7afce9184c16ebb65f16c
  Restoring /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fsproj
  Starting restore process.
  Total time taken: 0 milliseconds
  Shared -> /tmp/p/f#/guido-learns-fsharp5/src/Shared/bin/Debug/net7.0/Shared.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.98
server: /tmp/p/f#/guido-learns-fsharp5/src/Server> dotnet watch run
client: /tmp/p/f#/guido-learns-fsharp5/src/Client> dotnet fable watch --run webpack-dev-server
/tmp/p/f#/guido-learns-fsharp5/src/Server> "dotnet" watch run (In: false, Out: true, Err: true)
/tmp/p/f#/guido-learns-fsharp5/src/Client> "dotnet" fable watch --run webpack-dev-server (In: false, Out: true, Err: true)
client: Fable: F# to JS compiler 3.2.1
client: Thanks to the contributor! @josselinauguste
client: .> dotnet restore Client.fsproj
client:   Determining projects to restore...
client:   Paket version 7.2.1+8e4eb74b42fbd45f39f7afce9184c16ebb65f16c
client:   Restoring /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fsproj
client:   Starting restore process.
client:   Total time taken: 0 milliseconds
client:   All projects are up-to-date for restore.
client: Parsing Client.fsproj...
server: dotnet watch 🚀 Started
client: Initializing F# compiler...
client: Compiling Client.fsproj...
client: F# compilation finished in 1642ms
client: Fable compilation finished in 11ms
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(111,11): (111,14) warning FSHARP: Incomplete pattern matches on this expression. (code 25)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(115,11): (115,15) warning FSHARP: Uppercase variable identifiers should not generally be used in patterns, and may indicate a missing open declaration or a misspelt pattern name. (code 49)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(119,11): (120,28) warning FSHARP: This rule will never be matched (code 26)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Extensions.fs(8,12): (8,16) error FSHARP: The value, namespace, type or module 'List' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Extensions.fs(9,12): (9,16) error FSHARP: The value, namespace, type or module 'List' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Extensions.fs(10,12): (10,16) error FSHARP: The value, namespace, type or module 'List' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Extensions.fs(14,17): (14,21) error FSHARP: The value, namespace, type or module 'List' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(4,17): (4,22) error FSHARP: The type 'float' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(5,18): (5,23) error FSHARP: The type 'float' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(8,13): (8,19) error FSHARP: The type 'string' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(9,15): (9,21) error FSHARP: The type 'string' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(10,16): (10,23) error FSHARP: The type 'LatLong' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(13,17): (13,23) error FSHARP: The type 'string' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(14,17): (14,25) error FSHARP: The type 'Location' is not defined. Maybe you want one of the following:
client:    LocationResponse (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(15,26): (15,31) error FSHARP: The type 'float' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(17,1): (40,102) error FSHARP: The type referenced through 'System.Collections.IStructuralComparable' is defined in an assembly that is not referenced. You must add a reference to assembly 'The system type 'System.Collections.IStructuralComparable' was required but no referenced system DLL contained this type'. (code 74)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(46,20): (46,31) error FSHARP: The type 'WeatherType' is not defined. Maybe you want one of the following:
client:    WeatherResponse (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(47,27): (47,32) error FSHARP: The type 'float' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(50,19): (50,26) error FSHARP: The value or constructor 'sprintf' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(53,20): (53,26) error FSHARP: The type 'string' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(53,30): (53,35) error FSHARP: The type 'Async' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(54,19): (54,25) error FSHARP: The type 'string' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(54,29): (54,34) error FSHARP: The type 'Async' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(58,10): (58,16) error FSHARP: The namespace or module 'System' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(60,44): (60,50) error FSHARP: The type 'string' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(62,19): (62,24) error FSHARP: The value, namespace, type or module 'Regex' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(63,19): (63,24) error FSHARP: The value, namespace, type or module 'Regex' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(3,6): (3,12) error FSHARP: The namespace or module 'Elmish' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(5,6): (5,11) error FSHARP: The namespace or module 'Feliz' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(6,6): (6,11) error FSHARP: The namespace or module 'Feliz' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(7,6): (7,11) error FSHARP: The namespace or module 'Feliz' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(8,6): (8,11) error FSHARP: The namespace or module 'Feliz' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(9,6): (9,12) error FSHARP: The namespace or module 'Elmish' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(11,6): (11,11) error FSHARP: The namespace or module 'Fable' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(12,6): (12,12) error FSHARP: The namespace or module 'Shared' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(13,6): (13,11) error FSHARP: The namespace or module 'Bulma' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(14,11): (14,15) error FSHARP: The type 'Html' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(15,11): (15,16) error FSHARP: The type 'Bulma' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(21,17): (21,33) error FSHARP: The type 'LocationResponse' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(29,22): (29,28) error FSHARP: The type 'string' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(32,13): (32,19) error FSHARP: The type 'string' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(33,31): (33,37) error FSHARP: The type 'option' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(34,20): (34,31) error FSHARP: The type 'ServerState' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(35,38): (35,44) error FSHARP: The type 'option' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(46,33): (46,37) error FSHARP: The type 'list' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(72,1): (72,28) error FSHARP: The type referenced through 'System.Collections.IStructuralComparable' is defined in an assembly that is not referenced. You must add a reference to assembly 'The system type 'System.Collections.IStructuralComparable' was required but no referenced system DLL contained this type'. (code 74)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(76,22): (76,38) error FSHARP: The type 'DestinationIndex' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(76,41): (76,47) error FSHARP: The type 'string' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(77,25): (77,41) error FSHARP: The type 'DestinationIndex' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(78,25): (78,41) error FSHARP: The type 'DestinationIndex' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(78,44): (78,58) error FSHARP: The type 'ServerResponse' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(79,19): (79,35) error FSHARP: The type 'DestinationIndex' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(79,38): (79,41) error FSHARP: The type 'exn' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(85,19): (85,31) error FSHARP: The record label 'Destinations' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(86,12): (86,15) error FSHARP: The value, namespace, type or module 'Cmd' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(89,5): (89,13) error FSHARP: The value, namespace, type or module 'Remoting' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(90,8): (90,16) error FSHARP: The value, namespace, type or module 'Remoting' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(91,8): (91,16) error FSHARP: The value, namespace, type or module 'Remoting' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(93,35): (93,40) error FSHARP: The value or constructor 'async' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(110,24): (110,29) error FSHARP: The type 'Model' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(112,7): (112,21) error FSHARP: The pattern discriminator 'GetDestination' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(118,20): (118,23) error FSHARP: The value, namespace, type or module 'Cmd' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(119,11): (119,15) error FSHARP: The pattern discriminator 'Some' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(120,20): (120,23) error FSHARP: The value, namespace, type or module 'Cmd' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(122,7): (122,21) error FSHARP: The pattern discriminator 'GotDestination' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(126,17): (126,32) error FSHARP: The record label 'ValidationError' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(130,16): (130,19) error FSHARP: The value, namespace, type or module 'Cmd' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(138,7): (138,18) error FSHARP: The pattern discriminator 'TextChanged' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(142,17): (142,21) error FSHARP: The record label 'Text' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(149,16): (149,19) error FSHARP: The value, namespace, type or module 'Cmd' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(151,7): (151,15) error FSHARP: The pattern discriminator 'ErrorMsg' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(155,17): (155,28) error FSHARP: The record label 'ServerState' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(157,13): (157,24) error FSHARP: The value or constructor 'SimpleAlert' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(161,16): (161,26) error FSHARP: The value, namespace, type or module 'SweetAlert' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(163,20): (163,26) error FSHARP: The type 'string' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(163,51): (163,55) error FSHARP: The type 'list' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(164,5): (164,8) error FSHARP: The value or constructor 'box' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(172,5): (172,11) error FSHARP: The value or constructor 'navbar' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(200,5): (200,15) error FSHARP: The value, namespace, type or module 'PigeonMaps' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(211,21): (211,37) error FSHARP: The type 'LocationResponse' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(212,5): (212,15) error FSHARP: The value, namespace, type or module 'PigeonMaps' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(226,25): (226,40) error FSHARP: The type 'WeatherResponse' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(227,5): (227,8) error FSHARP: The value or constructor 'div' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(252,26): (252,42) error FSHARP: The type 'LocationResponse' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(253,5): (253,10) error FSHARP: The value or constructor 'table' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(286,12): (286,18) error FSHARP: The value or constructor 'string' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(288,47): (288,58) error FSHARP: The type 'Destination' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(289,5): (289,8) error FSHARP: The value or constructor 'box' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(395,40): (395,51) error FSHARP: The type 'Destination' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(435,17): (435,22) error FSHARP: The type 'Model' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(437,5): (437,8) error FSHARP: The value or constructor 'div' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/App.fs(3,6): (3,12) error FSHARP: The namespace or module 'Elmish' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/App.fs(4,6): (4,12) error FSHARP: The namespace or module 'Elmish' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/App.fs(7,6): (7,12) error FSHARP: The namespace or module 'Elmish' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/App.fs(8,6): (8,12) error FSHARP: The namespace or module 'Elmish' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/App.fs(11,1): (11,8) error FSHARP: The value, namespace, type or module 'Program' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/App.fs(13,4): (13,11) error FSHARP: The value, namespace, type or module 'Program' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/App.fs(15,4): (15,11) error FSHARP: The value, namespace, type or module 'Program' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/App.fs(17,4): (17,11) error FSHARP: The value, namespace, type or module 'Program' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/App.fs(19,4): (19,11) error FSHARP: The value, namespace, type or module 'Program' is not defined. (code 39)
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Extensions.fs(1,1): error EXCEPTION: Cannot find implementation file /tmp/p/f#/guido-learns-fsharp5/src/Shared/Extensions.fs
client: /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs(1,1): error EXCEPTION: Cannot find implementation file /tmp/p/f#/guido-learns-fsharp5/src/Shared/Shared.fs
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs(1,1): error EXCEPTION: Cannot find implementation file /tmp/p/f#/guido-learns-fsharp5/src/Client/Index.fs
client: /tmp/p/f#/guido-learns-fsharp5/src/Client/App.fs(1,1): error EXCEPTION: Cannot find implementation file /tmp/p/f#/guido-learns-fsharp5/src/Client/App.fs
client: Watching ..
```

**Comment by smoothdeveloper** [comment]
@daveyostcom yes I saw the same, unfortunately it is occurring on the fable side and I can't dig into it.

I think the PR improves the situation from the current state in the main branch, but unfortunately can't do much more.

**Comment by daveyostcom** [comment]
Thanks so much for your help!

**Comment by dsyme** [comment]
Thanks for looking at this!

Might just be easier to move the sample fully to the latest SAFE stack

**Comment by dsyme** [comment]
@daveyostcom @smoothdeveloper Should I merge this?

**Comment by daveyostcom** [comment]
Hi Don,

It does seem to be a move in the right direction, but the setup still fails somehow in the fable compile.  Might be an easy fix for someone who knows their way around, I hope.

The video with Guido is such an amazing thing that I watched it a  second time only when I felt I had enough familiarity with your beautiful language to fully appreciate it in detail.  I was not disappointed!  I’m looking forward to even more fun to play with the example myself, but it seems too daunting at the moment to figure out why it doesn’t work.

This problem is not an isolated case with Fable. All of the various tutorials suffer from bit rot.  Seems to me the F# foundation should host a master dashboard of all of the introductory paths into major pieces of the F# ecosystem and make sure they all stay green or are marked as dead when abandoned so newcomers don’t beat their head against them.  Scott’s wonderful site is the biggest problem, as it is very out of date.  The state of affairs today with introductory material is not a good look. It makes it hard to sell decision makers on F#.

OCaml seems very well organized and gets funding from some (one?) big users.  It would be great if the F# foundation could be at least as well funded.

Best,

Dave

**Comment by smoothdeveloper** [comment]
@dsyme, I'd merge as it makes `dotnet build` work out of the box.

For updating other packages, I'm unsure if the dependencies work with fable 4.

The saturn side of things seems to not need any change.

There is value in keeping the overall solution in shape and not churn it too much:
* the video is still drawing attention
* easier for newcomers if the code is overall the same
* a code dojo doesn't have to represent bleeding edge

@daveyostcom thanks for the great feedback, it makes sense, but alas, people who contribute all the great work around technical writing, and the underlying libraries, infrastructure, are I guess, spread thin.

If decision makers can't buy into F# wholesale, it is still possible to consider it for a subset, "testing the waters".

You may also evaluate WebSharper.

The properties of F# code, for the core domain and logic, are worth the effort it takes to get it adopted, especially if dotnet for backend has appeal.

For the "leafs" of the ecosystem, it depends preference of the team, and how much the decision makers rely on it versus feel need to make decision for it.

**Comment by dsyme** [comment]
@smoothdeveloper @daveyostcom I'd be happy to move this over to https://github.com/fsprojects if you'd like to be co-maintainers on it?  It is a nice dojo

**Pull request merged**
